#spring:
#  profiles:
#    active: dev
#

server:
  port: 8080

spring:
  datasource:
    username: root
    password: Jay@123456
    url: jdbc:mysql://localhost:3306/test_user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.mybatis.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug